name: unit-tests

on: [push, pull_request]

env:
  RUSTFLAGS: '-Dwarnings'
  RUSTDOCFLAGS: '-Drustdoc::broken_intra_doc_links'
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            deps: sudo apt update; sudo apt install -y gcc-multilib
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          override: true
      - run: ${{ matrix.deps }}
      - run: cargo test
      - run: cargo test --release

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo doc
